declare module "preact/jsx-runtime" {
  namespace JSX {
    interface IntrinsicElements {
      div: Record<string, unknown>;
      header: Record<string, unknown>;
      main: Record<string, unknown>;
      span: Record<string, unknown>;
      button: Record<string, unknown>;
      form: Record<string, unknown>;
      input: Record<string, unknown>;
      select: Record<string, unknown>;
      option: Record<string, unknown>;
      label: Record<string, unknown>;
      textarea: Record<string, unknown>;
      a: Record<string, unknown>;
      h1: Record<string, unknown>;
      p: Record<string, unknown>;
      ul: Record<string, unknown>;
      li: Record<string, unknown>;
      svg: Record<string, unknown>;
      path: Record<string, unknown>;
      g: Record<string, unknown>;
      circle: Record<string, unknown>;
      rect: Record<string, unknown>;
      line: Record<string, unknown>;
      polyline: Record<string, unknown>;
      polygon: Record<string, unknown>;
      ellipse: Record<string, unknown>;
      text: Record<string, unknown>;
      tspan: Record<string, unknown>;
      defs: Record<string, unknown>;
      clipPath: Record<string, unknown>;
      use: Record<string, unknown>;
      symbol: Record<string, unknown>;
      linearGradient: Record<string, unknown>;
      radialGradient: Record<string, unknown>;
      stop: Record<string, unknown>;
      mask: Record<string, unknown>;
      filter: Record<string, unknown>;
      feGaussianBlur: Record<string, unknown>;
      img: Record<string, unknown>;
      section: Record<string, unknown>;
      article: Record<string, unknown>;
      nav: Record<string, unknown>;
      aside: Record<string, unknown>;
      footer: Record<string, unknown>;
      fieldset: Record<string, unknown>;
      legend: Record<string, unknown>;
      "fluent-button": Record<string, unknown>;
      "fluent-text-input": Record<string, unknown>;
      "fluent-text-field": Record<string, unknown>;
      "fluent-textarea": Record<string, unknown>;
      "fluent-dropdown": Record<string, unknown>;
      "fluent-select": Record<string, unknown>;
      "fluent-option": Record<string, unknown>;
      "fluent-card": Record<string, unknown>;
      "fluent-badge": Record<string, unknown>;
    }
  }
}
